version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:13"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - ci
      - dependabot
      - deprecation
    commit-message:
      prefix: ci
      include: scope
    pull-request-branch-name:
      separator: "/"
    groups:
      github-actions:
        patterns:
          - "*"
